### ISSUE TITLE
Implement more advanced Dialog system

### ISSUE THREAD

**Issue by cofl** [HuskyGameDev/2019f-team10#34]
Requirements:

- Supports branching dialog
    - Player Decisions (maybe?)
    - Automatic conditions (has item, variable is set, etc...)
- Easy to read and edit
- Allows setting variables after visiting certain lines in the dialog, and other actions

**Comment by cofl** [comment]
It may be possible to use YAML for this.

A possible YAML file could looks like

```yaml
entry:
  lines:
    - branch:
      - condition: Not(F3_Has_Talked_To_Mazie)
        goto: Main
      - goto: Return
Main:
  - set:
      F3_Has_Talked_To_Mazie: true
  - actor: Mazie
    text:
      - "I'm so tired..."
      - "Do you have any candy for me?"
  - actor: Player
    text: "What?"
  - goto: Return
Return:
  - actor: Mazie
    text: Candy?
  - branch:
    - condition: HasItem(F3_Study_Candy)
      goto: Player has the candy
    - goto: Player does not have the candy
Player has the candy:
  - actor: Player
    text: Oh! I have one here for you!
    action: RemoveItem(F3_Study_Candy)
Player does not have the candy:
  - actor: Player
    text:
      - <i>I should find a candy.</i>
      - <i>Maybe there's one in the storage room?</i>
```

Then, instead of setting the dialog in the inspector, you would link to a dialog file, and any changes to the dialog wouldn't modify the scene.
